version: '3'

services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data


  api:
    image: node:alpine
    volumes:
      - ./api:/api
    working_dir: /api
    depends_on:
      - postgresql
    environment:
      NODE_ENV: development
    ports:
      - 8080:80
    command: npm run start


  app:
    image: node:alpine
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - api
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start
